---
# tasks file for OULibOps.EL9-baseline


- name: Check for CRB.
  ansible.builtin.command:
    cmd: dnf repolist
  register: dnf_repolist
  changed_when: false

- name: Ensure the CRB repository is enabled.
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled crb  -y
    creates:
  become: true
  when: dnf_repolist.stdout.find("crb") == -1

- name: Ensure that EPEL is enabled.
  ansible.builtin.dnf:
    name:
      - epel-release
      - epel-next-release
    state: present
  become: true

- name: Install basic sysadmin tools.
  ansible.builtin.dnf:
    name:
      - ack
      - bind-utils  # includes dig
      - curl
      - git
      - htop
      - nano
      - policycoreutils-python-utils # includes audit2why
      - tmux
      - tree
      - vim
      - wget
    state: present
  become: true

- name: Install AWS tools.
  ansible.builtin.dnf:
    name:
      - awscli2
    state: present
  become: true

- name: Set hostname based on Name tag (if present).
  ansible.builtin.hostname:
    name: "{{ tags.Name }}"
    use: systemd
  become: true
  when: ( tags.Name is defined) and (tags.Name|length > 0)

- name: Allow passwordless sudo for wheel group.
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL)  NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true
